version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: planetarion
      POSTGRES_USER: planetarion_user
      POSTGRES_PASSWORD: planetarion_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planetarion_user -d planetarion"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./src
      dockerfile: ./backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://planetarion_user:planetarion_password@db:5432/planetarion
      FLASK_ENV: development

    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: ["python", "-m", "backend.app"]

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  postgres_data:
